// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bayatfzjzfmhfedazgbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJheWF0ZnpqemZtaGZlZGF6Z2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODIxOTUsImV4cCI6MjA1NTU1ODE5NX0.1t80jUxkUL42oRyLrtdqGYjLl4GH2Qh3FnKrbxwVmDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);